### ISSUE TITLE
Change scroll marker color for searches

### ISSUE THREAD

**Issue by bunnyroo** [surdu/scroll-marker#22]
Not really a bug, but hoping someone could help me out. I would like to change the scroll marker color from the default yellow to a different color.

![search-scrollbar](https://user-images.githubusercontent.com/5052036/85060537-41f57600-b15a-11ea-9f86-ffd894dfb8df.png)

Is that possible and if so, what would be the css rule to add to my stylesheet?

**Comment by surdu** [comment]
```css
.find-marker-layer .scroll-marker {
	background-color: magenta !important;
}
```
Substitute `.find-marker-layer` with `.highlight-selected-selected-marker-layer` (I didn't named this 😝 ) for [highlight-selected](https://atom.io/packages/highlight-selected) and with `.link-scroll-marker-warn` / `.lint-scroll-marker-error` / `.link-scroll-marker-info` for [lint-scroll-marker](https://atom.io/packages/lint-scroll-marker)

**Comment by surdu** [comment]
PS: added this [to the documentation](https://github.com/surdu/scroll-marker#customise-marker-color)

**Comment by bunnyroo** [comment]
Thanks!

**Comment by surdu** [comment]
No problemo ;)
