### ISSUE TITLE
[bug] marker position wrong when "scroll past end" is activated in language-fortran

### ISSUE THREAD

**Issue by santa-klaus** [surdu/scroll-marker#27]
Okay, I don't know where this should be adressed, but the package `language-fortran` contains the option "Scroll Past End" allowing to scroll past the end of a document. If this is activated, the marker position will be messed up.

**Comment by surdu** [comment]
How is this option different from the "Scroll Past End" option from the editor?

**Comment by santa-klaus** [comment]
Oh, I didn't know that one existed, sorry! New user here :) It overwrites those settings based on which fortran grammar you are using, i.e. fixed form vs. free form.

**Comment by surdu** [comment]
If you use the one from the editor, the markers should display just fine. 

Obviously, it's not scalable for my plugin to now look for this option in a million of extensions that choose to reinvent the wheel, like this fortran extensions seems to do.

Please use the one in the editor, and let me know if both has the same effect for you as the one in fortran plugin, and that the markers show properly now.

**Comment by santa-klaus** [comment]
Yes, I understand that. Sorry! Seems like the place to report this bug is that extension. 

As a reference for future people possibly coming across this:
As the fortran extensions' setting overwrites the editor's one, you have to make sure that they are the same for the marker placement to work properly.
