### ISSUE TITLE
Not showing in scroll bar

### ISSUE THREAD

**Issue by jano23** [surdu/scroll-marker#28]
Windows 10
Atom ver 1.53.0
scroll-marker 0.3.5
find-scroll-marker 0.1.3

I am not seeing anything in the scroll bar.
I searched for installed packages that have anything to do with scroll and disabled them. Except  for the two mentioned above, of course.
Changed UI and Syntax themes back to Atom Dark

**Comment by jano23** [comment]
I narrowed it down to php files.
It works with other file types just not php
I do have language-php package installed

**Comment by surdu** [comment]
I don't seem to manage to reproduce your issue:

<img width="749" alt="Screenshot 2020-11-23 at 23 28 07" src="https://user-images.githubusercontent.com/11520795/100017460-996fd000-2de3-11eb-902d-7075b4450ab4.png">

**Comment by jano23** [comment]
You are welcome to borrow my computer :-)
I'm hell bent on finding out what is causing it. I have a Windows 10 laptop and it behaves correctly there. I am in the process of comparing both to see if there is anything different in all the Settings, Packages, etc. Haven't found anything yet but I'll post if I hit on the mystery

**Comment by surdu** [comment]
One thing that you could try is to open the editor in development mode (`atom --dev .`) and open the development tools (<kbd>Ctrl+Shift+I</kbd>). There might be some error messages in there that will give you a hint about the issue.

**Comment by jano23** [comment]
I'll try that.
In the mean time I did find this out. If I open a file and then do a "Split Right". the right hand pane does show the markers.

**Comment by jano23** [comment]
I looked at the error messages when I start Atom and as I use Search.
There are some cautions and errors but nothing conclusive or that I am not seeing in both computers. No new ones as I do searches

**Comment by jano23** [comment]
The workaround I have figured out is to open a file, do a "Split Right" then close that file. It will then work no matter how many files I open/close. Until I restart Atom

**Comment by jano23** [comment]
I resolved the issue by using Revo Uninstaller Pro and completely removing any traces of Atom then reinstalling.
I cheated some by copying packages and .atom over from the laptop.
Now it is working as it should.
This package is very helpful to me!

**Comment by surdu** [comment]
Glad to hear that your problem is resolved and that the package is useful to you and many others ❤️ 

In the meantime, I'll close this issue. Please re-open if you feel the issue still stands.
