### ISSUE TITLE
Doesn't work in Atom 1.32.2

### ISSUE THREAD

**Issue by Torniojaws** [surdu/scroll-marker#6]
Atom 1.32.2 x64 in Ubuntu 18.04.1
scroll-marker version 0.2.0

After installing, I restarted all Atom instances, but still it doesn't seem to add the markers:
![image](https://user-images.githubusercontent.com/5442750/48933756-238db100-ef0a-11e8-9e5f-07f3a41ea162.png)

I also have the symbols-list plugin, but even with it disabled, the markers don't appear. No errors appear in the Atom console.

**Comment by surdu** [comment]
Do you have [lint-scroll-marker](https://atom.io/packages/lint-scroll-marker) installed ?

**Comment by Torniojaws** [comment]
Okay, installed it, and got the error line to show up, but the git diff (eg. the yellow) lines don't show up. Is that supported?

**Comment by surdu** [comment]
Awesome! scroll-marker plugin only provides the capability to show markers on the scrollbar. You will need additional plugins to show the actual markers. Please [see here](https://github.com/surdu/scroll-marker#packages-powered-by-scroll-marker) for a list of other scroll-marker plugins. 

For now, there is no plugin to show diffs, but you are more than welcome to start writing one following the [documentation here](https://github.com/surdu/scroll-marker#developer-documentation).

Thank you very much for your feedback! Much appreciated!

**Comment by surdu** [comment]
PS: I've created #7 which once implemented should help first time users not have your problem.
