### ISSUE TITLE
Inform users they need additional plugins

### ISSUE THREAD

**Issue by surdu** [surdu/scroll-marker#7]
It may not be apparent to first time users that they also need additional plugins to make this one do something useful. 

One idea would be to show a notification with this information, and capability to either jump to search with prefilled text or open a webpage to the list of scroll-marker plugins.

**Comment by Torniojaws** [comment]
Personally, I would bundle the two plugins into one :) Is there some particular reason to keep them separated?

**Comment by surdu** [comment]
Fixed by #10
